/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Blockbuster2;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author ejb5674
 * 
 * Date: April 1, 2019
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSearchBar = new javax.swing.JTextField();
        jbAdvancedSearch = new javax.swing.JButton();
        jbSearchButton = new javax.swing.JButton();
        jpMovieDisplayer = new javax.swing.JPanel();
        jlMovieImage3 = new javax.swing.JLabel();
        jlMovieImage1 = new javax.swing.JLabel();
        jlMovieImage2 = new javax.swing.JLabel();
        jlSearchMoviesLabel = new javax.swing.JLabel();
        jlTrendingMoviesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlockBuster2 Home Screen");
        setBackground(new java.awt.Color(153, 204, 255));

        jtfSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchBarActionPerformed(evt);
            }
        });

        jbAdvancedSearch.setText("Advanced Search");
        jbAdvancedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdvancedSearchActionPerformed(evt);
            }
        });

        jbSearchButton.setBackground(new java.awt.Color(0, 51, 255));
        jbSearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSearchButton.setForeground(new java.awt.Color(255, 255, 51));
        jbSearchButton.setText("Go!");
        jbSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchButtonActionPerformed(evt);
            }
        });

        jlMovieImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blockbuster2/images/CaptainMarvel_1.jpg"))); // NOI18N

        ImageIcon movieImage1 = new ImageIcon("Blockbuster2.images\\MonstersInc.jpg");
        jlMovieImage1.setIcon(movieImage1);
        jlMovieImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blockbuster2/images/PetSemetary.jpg"))); // NOI18N

        jlMovieImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blockbuster2/images/US_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jpMovieDisplayerLayout = new javax.swing.GroupLayout(jpMovieDisplayer);
        jpMovieDisplayer.setLayout(jpMovieDisplayerLayout);
        jpMovieDisplayerLayout.setHorizontalGroup(
            jpMovieDisplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMovieDisplayerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlMovieImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jlMovieImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jlMovieImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMovieDisplayerLayout.setVerticalGroup(
            jpMovieDisplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMovieDisplayerLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jpMovieDisplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMovieImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMovieImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMovieImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jlSearchMoviesLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlSearchMoviesLabel.setText("Search Movies:");

        jlTrendingMoviesLabel.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        jlTrendingMoviesLabel.setForeground(new java.awt.Color(51, 51, 255));
        jlTrendingMoviesLabel.setText("Trending Movies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jlSearchMoviesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdvancedSearch)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jlTrendingMoviesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jpMovieDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlTrendingMoviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMovieDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSearchMoviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdvancedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchBarActionPerformed

    private void jbAdvancedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdvancedSearchActionPerformed
        
        SearchWindow advancedSearch = new SearchWindow();
        advancedSearch.setVisible(true);
        
    }//GEN-LAST:event_jbAdvancedSearchActionPerformed

    private void jbSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchButtonActionPerformed
        Search search = OmdbConnection.getMoviesByTitle(jtfSearchBar.getText());
        SearchResultWindow srw = new SearchResultWindow();
        DefaultListModel resultModel = new DefaultListModel();
        for(int i = 0; i < search.Search.size(); i++){
            resultModel.addElement(search.Search.get(i).Title);
        }
        srw.resultList.setModel(resultModel);
        srw.setVisible(true);
    }//GEN-LAST:event_jbSearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdvancedSearch;
    private javax.swing.JButton jbSearchButton;
    private javax.swing.JLabel jlMovieImage1;
    private javax.swing.JLabel jlMovieImage2;
    private javax.swing.JLabel jlMovieImage3;
    private javax.swing.JLabel jlSearchMoviesLabel;
    private javax.swing.JLabel jlTrendingMoviesLabel;
    private javax.swing.JPanel jpMovieDisplayer;
    private javax.swing.JTextField jtfSearchBar;
    // End of variables declaration//GEN-END:variables
}
