/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Blockbuster2;

/**
 *
 * @author thb5075
 */
public class SearchWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchWindow
     */
    public SearchWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTitleLabel = new javax.swing.JLabel();
        searchGenreLabel = new javax.swing.JLabel();
        searchRatingLabel = new javax.swing.JLabel();
        searchReviewLabel = new javax.swing.JLabel();
        searchReviewField = new javax.swing.JTextField();
        searchActorLabel = new javax.swing.JLabel();
        searchActorField = new javax.swing.JTextField();
        searchDirectorLabel = new javax.swing.JLabel();
        searchDirectorField = new javax.swing.JTextField();
        searchLengthLabel = new javax.swing.JLabel();
        searchLengthField = new javax.swing.JTextField();
        searchMovieLabel = new javax.swing.JLabel();
        searchMovieField = new javax.swing.JTextField();
        searchGenreField = new javax.swing.JComboBox<>();
        searchRatingField = new javax.swing.JComboBox<>();
        searchReviewSelection = new javax.swing.JComboBox<>();
        searchLengthSelection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchTitleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchTitleLabel.setText("Search:");

        searchGenreLabel.setText("Genre");

        searchRatingLabel.setText("Rating");

        searchReviewLabel.setText("Reviews");

        searchReviewField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchReviewFieldActionPerformed(evt);
            }
        });

        searchActorLabel.setText("Actor Last Name");

        searchDirectorLabel.setText("Director Last Name");

        searchDirectorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDirectorFieldActionPerformed(evt);
            }
        });

        searchLengthLabel.setText("Length (Minutes)");

        searchLengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLengthFieldActionPerformed(evt);
            }
        });

        searchMovieLabel.setText("Movie Title");

        searchMovieField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMovieFieldActionPerformed(evt);
            }
        });

        searchGenreField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Preference" }));

        searchRatingField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Preference", "G", "PG", "PG-13", "R" }));

        searchReviewSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Above", "Exactly", "Below" }));

        searchLengthSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Above", "Exactly", "Below" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchGenreLabel)
                            .addComponent(searchRatingLabel)
                            .addComponent(searchReviewLabel)
                            .addComponent(searchActorLabel)
                            .addComponent(searchDirectorLabel)
                            .addComponent(searchLengthLabel)
                            .addComponent(searchMovieLabel))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchActorField)
                            .addComponent(searchDirectorField)
                            .addComponent(searchMovieField)
                            .addComponent(searchGenreField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchRatingField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchReviewSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchLengthSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchReviewField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(searchLengthField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchMovieLabel)
                    .addComponent(searchMovieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchGenreLabel)
                    .addComponent(searchGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchRatingLabel)
                    .addComponent(searchRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchReviewLabel)
                    .addComponent(searchReviewField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchReviewSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchActorLabel)
                    .addComponent(searchActorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDirectorLabel)
                    .addComponent(searchDirectorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLengthLabel)
                    .addComponent(searchLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLengthSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchReviewFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchReviewFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchReviewFieldActionPerformed

    private void searchDirectorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDirectorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDirectorFieldActionPerformed

    private void searchMovieFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMovieFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMovieFieldActionPerformed

    private void searchLengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLengthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLengthFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchActorField;
    private javax.swing.JLabel searchActorLabel;
    private javax.swing.JTextField searchDirectorField;
    private javax.swing.JLabel searchDirectorLabel;
    private javax.swing.JComboBox<String> searchGenreField;
    private javax.swing.JLabel searchGenreLabel;
    private javax.swing.JTextField searchLengthField;
    private javax.swing.JLabel searchLengthLabel;
    private javax.swing.JComboBox<String> searchLengthSelection;
    private javax.swing.JTextField searchMovieField;
    private javax.swing.JLabel searchMovieLabel;
    private javax.swing.JComboBox<String> searchRatingField;
    private javax.swing.JLabel searchRatingLabel;
    private javax.swing.JTextField searchReviewField;
    private javax.swing.JLabel searchReviewLabel;
    private javax.swing.JComboBox<String> searchReviewSelection;
    private javax.swing.JLabel searchTitleLabel;
    // End of variables declaration//GEN-END:variables
}
